vich_uploader:
    db_driver: orm # Utilisation d'ORM (Doctrine)

    metadata:
        type: attribute 
        
    mappings:
        # Configurez ici vos différents types de fichiers
        # Example pour les documents
        documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
