<?php

namespace App\Form;

use App\Entity\CapitalisationPartII;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CapitalisationPartIIType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('A1', null, ['label' => 'A1 - Titre du projet  ',])
            ->add('A5', null, ['label' => 'A5 - Région d\'intervention  ',])
            ->add('A10', null, ['label' => 'A10 - Projet No.',])
            ->add('A10a', null, ['label' => 'A10a - Projet No. Pour Confirmation.',])
            ->add('A11', null, ['label' => 'A11 - Fonds',])
            ->add('A12', null, ['label' => 'A12 - Phases',])
            ->add('A13', null, ['label' => 'A13 - Paysages',])
            ->add('A19', null, ['label' => 'A19 - Domaine d\'intervention',])
            ->add('A33', null, ['label' => 'A33 - Année de remplissage de l\'outils',])
            ->add('A34', null, ['label' => 'A34 - Numero trimestre : de 0 (état zéro) à 20',])
            ->add('L1_1', null, ['label' => 'L1_1 - Y-a-t il de bonne pratique pendant la mise en œuvre du projet?',])
            ->add('L1_13', null, ['label' => 'L1_13 - Décrire le domaine thématique de la bonne pratique? ',])
            ->add('L3_1', null, ['label' => 'L3_1 - Quels sont les facteurs déterminants qui ont fait naître les bonnes pratiques?',])
            ->add('L3_2', null, ['label' => 'L3_2 - Quels sont les buts de l’initiative qui a fait évoluer positivement  les pratiques?',])
            ->add('L3_3', null, ['label' => 'L3_3 - Indiquez pour chaque étape l’année ou la période avec l’état de la connaissance à l’époque?',])
            ->add('L3_4', null, ['label' => 'L3_4 - Quels sont les principaux problèmes rencontrés par les bénéficiaires ou les communautés? ',])
            ->add('L3_5', null, ['label' => 'L3_5 - Quels sont les blocages générés par ces problèmes sur le plan économique ?',])
            ->add('L3_6', null, ['label' => 'L3_6 - Quels sont les blocages générés par ces problèmes sur le plan social ?',])
            ->add('L3_7', null, ['label' => 'L3_7 - Quels sont les blocages générés par ces problèmes sur le plan culturel ?',])
            ->add('L3_8', null, ['label' => 'L3_8 - Quels sont les blocages générés par ces problèmes sur le plan gouvernance ?',])
            ->add('L3_9', null, ['label' => 'L3_9 - Quels sont les blocages générés par ces problèmes sur autre plan ?',])
            ->add('L3_10', null, ['label' => 'L3_10 - Genèse du ou des bonnes pratiques (Résumé)',])
            ->add('L3_11', null, ['label' => 'L3_11 - Quel est le type de la bonne pratique ?',])
            ->add('L3_11_autre', null, ['label' => 'L3_11_autre - Si autre ?',])
            ->add('L3_12', null, ['label' => 'L3_12 - Quelle  est la bonne pratique technique en question?',])
            ->add('L3_13', null, ['label' => 'L3_13 - Est-ce qu’il s’agit d’une amélioration de la pratique locale des communautés?',])
            ->add('L3_14', null, ['label' => 'L3_14 - Veuillez décrire la procédure relative à la technique',])
            ->add('L3_15', null, ['label' => 'L3_15 - Qui fais quoi?',])
            ->add('L3_16', null, ['label' => 'L3_16 - Quand?',])
            ->add('L3_17', null, ['label' => 'L3_17 - Décrire la méthodologie, approche, démarche adoptée?',])
            ->add('L3_18', null, ['label' => 'L3_18 - Quels moyens requis par étape?',])
            ->add('L3_18_autre', null, ['label' => 'L3_18_autre - Si autre ?',])
            ->add('L3_19', null, ['label' => 'L3_19 - Quels outils utilisés?',])
            ->add('L3_20', null, ['label' => 'L3_20 - Quelles précautions à prendre?',])
            ->add('L3_21', null, ['label' => 'L3_21 - Quels sont les conditions requises',])
            ->add('L3_22', null, ['label' => 'L3_22 - Quels avantages comparatifs par rapport à la situation antérieure?',])
            ->add('L3_22_autre', null, ['label' => 'L3_22_autre - Si autre ?',])
            ->add('L3_23', null, ['label' => 'L3_23 - Quelles sont les nouvelles idées, nouvelles pratiques techniques que les autres peuvent essayer de mettre en pratique ?',])
            ->add('L3_24', null, ['label' => 'L3_24 - Décrire le type de la bonne pratique (Résumé) : Technique',])
            ->add('L3_25', null, ['label' => 'L3_25 - Quoi à gérer avec la bonne pratique?',])
            ->add('L3_26', null, ['label' => 'L3_26 - Comment se fait l’amélioration de la technique de gestion?',])
            ->add('L3_27', null, ['label' => 'L3_27 - Décrire la méthodologie, approche, démarche adoptée?',])
            ->add('L3_28', null, ['label' => 'L3_28 - Quels sont les moyens requis par étape ?',])
            ->add('L3_28_autre', null, ['label' => 'L3_28_autre - Si autre ?',])
            ->add('L3_29', null, ['label' => 'L3_29 - Quels outils à utiliser?',])
            ->add('L3_30', null, ['label' => 'L3_30 - Quelles précautions à prendre?',])
            ->add('L3_31', null, ['label' => 'L3_31 - Quelles sont les conditions requises pour appliquer la bonne pratique?',])
            ->add('L3_32', null, ['label' => 'L3_32 - Quels avantages comparatifs par rapport à la situation antérieure?',])
            ->add('L3_33', null, ['label' => 'L3_33 - Quelles précautions à prendre ? ',])
            ->add('L3_34', null, ['label' => 'L3_34 - Quelles sont les nouvelles méthodes, nouvelles approches, nouveaux outils…. que les autres peuvent essayer de mettre en pratique ?',])
            ->add('L3_35', null, ['label' => 'L3_35 - Décrire le type de la bonne pratique (Résumé) : Gestion',])
            ->add('L3_36', null, ['label' => 'L3_36 - Quelle est la gouvernance améliorée?',])
            ->add('L3_37', null, ['label' => 'L3_37 - Quelle règle de base de la gouvernance à appliquer?',])
            ->add('L3_38', null, ['label' => 'L3_38 - Quel texte en vigueur ou loi touché?',])
            ->add('L3_39', null, ['label' => 'L3_39 - Décrire la méthodologie, approche, démarche adoptée?',])
            ->add('L3_40', null, ['label' => 'L3_40 - Est-ce qu’il s’agit d’une amélioration de la gouvernance traditionnelle?',])
            ->add('L3_41', null, ['label' => 'L3_41 - Laquelle ?',])
            ->add('L3_42', null, ['label' => 'L3_42 - Quels acteurs concernés par la gouvernance améliorée?',])
            ->add('L3_43', null, ['label' => 'L3_43 - Qui fait quoi?',])
            ->add('L3_44', null, ['label' => 'L3_44 - Quel règlement?',])
            ->add('L3_45', null, ['label' => 'L3_45 - Est-ce qu’il y a des actes écrits  ou verbaux ou autres matière qui marque la gouvernance ?',])
            ->add('L3_46', null, ['label' => 'L3_46 - Quelles sont les conditions requises pour bien appliquer la bonne pratique',])
            ->add('L3_47', null, ['label' => 'L3_47 - Quelles précautions prises?',])
            ->add('L3_48', null, ['label' => 'L3_48 - Quels outils développés ?',])
            ->add('L3_49', null, ['label' => 'L3_49 - Quelles sont les nouvelles organisations, nouvelles approches, nouvelles règles … que les autres peuvent mettre en pratique ?',])
            ->add('L3_50', null, ['label' => 'L3_50 - Décrire le type de la bonne pratique (Résumé) : Gouvernance',])
            ->add('L3_51', null, ['label' => 'L3_51 - Quelle pratique de communication développée ?',])
            ->add('L3_52', null, ['label' => 'L3_52 - Décrire la méthodologie?',])
            ->add('L3_53', null, ['label' => 'L3_53 - Décrire l\'approche?',])
            ->add('L3_54', null, ['label' => 'L3_54 - Décrire la démarche adopté?',])
            ->add('L3_55', null, ['label' => 'L3_55 - Quel type de communication?',])
            ->add('L3_55_autre', null, ['label' => 'L3_55_autre - Si autre ?',])
            ->add('L3_56', null, ['label' => 'L3_56 - Qui assure la communication vers qui?',])
            ->add('L3_57', null, ['label' => 'L3_57 - Quels outils de communication?',])
            ->add('L3_58', null, ['label' => 'L3_58 - Quels canaux de communication : marché, lieu public, réunion communautaire, pratique de culte traditionnel, …',])
            ->add('L3_58_autre', null, ['label' => 'L3_58_autre - Si autre ?',])
            ->add('L3_59', null, ['label' => 'L3_59 - Quelles sont les conditions requises pour bien appliquer la bonne pratique?',])
            ->add('L3_60', null, ['label' => 'L3_60 - Quelle précautions prises?',])
            ->add('L3_61', null, ['label' => 'L3_61 - Quels sont les nouveaux éléments relatifs à la communication que les autres peuvent mettre en pratiques (acteurs, messages, outils, canaux, supports, …. ?',])
            ->add('L3_62', null, ['label' => 'L3_62 - Décrire le type de la bonne pratique (Résumé) : Communication',])
            ->add('L3_63', null, ['label' => 'L3_63 - Quel outil NTIC utilisé?',])
            ->add('L3_64', null, ['label' => 'L3_64 - Décrire la méthodologie?',])
            ->add('L3_65', null, ['label' => 'L3_65 - Décrire l\'approche?',])
            ->add('L3_66', null, ['label' => 'L3_66 - Décrire la démarche adopté?',])
            ->add('L3_67', null, ['label' => 'L3_67 - Quels sont les connaissances de base requises pour pouvoir mettre en pratique la bonne pratique?',])
            ->add('L3_68', null, ['label' => 'L3_68 - Quels moyens requis ?',])
            ->add('L3_68_autre', null, ['label' => 'L3_68_autre - Si autre ?',])
            ->add('L3_69', null, ['label' => 'L3_69 - Quels matériels utilisés?',])
            ->add('L3_70', null, ['label' => 'L3_70 - Quelles conditions requises?',])
            ->add('L3_71', null, ['label' => 'L3_71 - Quelle nouvelle technologie, que les autres peuvent mettre en pratique ?  ',])
            ->add('L3_72', null, ['label' => 'L3_72 - Décrire le type de la bonne pratique (Résumé) : NTIC',])
            ->add('L3_73', null, ['label' => 'L3_73 - Quelle est la contribution de la bonne pratique au maintien de la biodiversité mondialement reconnue et des services écosystémiques bénéfiques pour la société',])
            ->add('L3_74', null, ['label' => 'L3_74 - Soutien à la réduction de l’émission de gaz à effet de serre (atténuation)?',])
            ->add('L3_75', null, ['label' => 'L3_75 - Accroissement de la capacité de résilience (adaptation) ?',])
            ->add('L3_76', null, ['label' => 'L3_76 - Est-ce qu’elle fait partie de la création de nouvelles sources d’énergie (éolienne, solaire, biogaz, autres à préciser ?',])
            ->add('L3_77', null, ['label' => 'L3_77 - Est-ce que la bonne pratique répond à la gestion durable du sol au sein du système de production ou d’un paysage forestier?',])
            ->add('L3_78', null, ['label' => 'L3_78 - Elimination progressive et réduction progressive des rejets de pesticides organiques',])
            ->add('L3_79', null, ['label' => 'L3_79 - Décrire en une phrase la spécificité de la thématique dans le type technique de la bonne pratique',])

            ->add('L3_120', null, ['label' => 'L3_120- Est-ce que la thématique traite les priorités suivantes?',])
            ->add('L3_121', null, ['label' => 'L3_121- Si renforcement de capacité des femmes, précisez?',])
            ->add('L3_122', null, ['label' => 'L3_122- Si autre, précisez',])
            ->add('L3_123', null, ['label' => 'L3_123- Décrire brièvement la thématique',])
            ->add('L3_124', null, ['label' => 'L3_124- Est-ce que la thématique traite les priorités suivantes?',])
            ->add('L3_125', null, ['label' => 'L3_125- Si genre, précisez?',])
            ->add('L3_126', null, ['label' => 'L3_126- Si autre, précisez',])
            ->add('L3_127', null, ['label' => 'L3_127- Décrire brièvement la thématique',])
            ->add('L3_128', null, ['label' => 'L3_128- Est-ce que la thématique traite les priorités suivantes?',])
            ->add('L3_129', null, ['label' => 'L3_129- Décrire brièvement la thématique',])

            ->add('L3_80', null, ['label' => 'L3_80 - Acteurs bénéficiaires de la bonne pratique ',])
            ->add('L3_81', null, ['label' => 'L3_81 - Qui est le leader du Fokonolona : Ampanjaka, olobe, mpitankazomanga, ….',])
            ->add('L3_82', null, ['label' => 'L3_82 - Nombre total',])
            ->add('L3_83', null, ['label' => 'L3_83 - Nombre désagrégé par sexe ',])
            ->add('L3_84', null, ['label' => 'L3_84 - Nombre désagrégé par classe d’âge ',])
            ->add('L3_85', null, ['label' => 'L3_85 - Nombre de Personne handicapé',])
            ->add('L3_86', null, ['label' => 'L3_86 - Nombre de Jeunes',])
            ->add('L3_87', null, ['label' => 'L3_87 - Nombre de Femmes',])
            ->add('L3_88', null, ['label' => 'L3_88 - Nombre total',])
            ->add('L3_89', null, ['label' => 'L3_89 - Nombre désagrégé par sexe ',])
            ->add('L3_90', null, ['label' => 'L3_90 - Nombre désagrégé par classe d’âge ',])
            ->add('L3_91', null, ['label' => 'L3_91 - Nombre d’année de transfert de gestion ',])
            ->add('L3_92', null, ['label' => 'L3_92 - Etat du transfert de gestion : nouveau, reconduit, ',])
            ->add('L3_93', null, ['label' => 'L3_93 - Nombre de Personne handicapé',])
            ->add('L3_94', null, ['label' => 'L3_94 - Nombre de Jeunes',])
            ->add('L3_95', null, ['label' => 'L3_95 - Nombre de Femmes',])
            ->add('L3_96', null, ['label' => 'L3_96 - Description de la coopérative : quelle spéculation, année de création Nombre total des membres ',])
            ->add('L3_97', null, ['label' => 'L3_97 - Nombre désagrégé par sexe ',])
            ->add('L3_98', null, ['label' => 'L3_98 - Nombre désagrégé par classe d’âge ',])
            ->add('L3_99', null, ['label' => 'L3_99 - Historique de la coopérative ',])
            ->add('L3_100', null, ['label' => 'L3_100 - Nombre de Personne handicapé',])
            ->add('L3_101', null, ['label' => 'L3_101 - Nombre de Jeunes',])
            ->add('L3_102', null, ['label' => 'L3_102 - Nombre de Femmes',])
            ->add('L3_103', null, ['label' => 'L3_103 - Domaine d’intervention des OSC',])
            ->add('L3_104', null, ['label' => 'L3_104 - Nombre total des membres ',])
            ->add('L3_105', null, ['label' => 'L3_105 - Nombre désagrégé par sexe ',])
            ->add('L3_106', null, ['label' => 'L3_106 - Nombre désagrégé par classe d’âge ',])
            ->add('L3_107', null, ['label' => 'L3_107 - Domaine d’intervention',])
            ->add('L3_108', null, ['label' => 'L3_108 - Combien d’OSC membres ',])
            ->add('L3_109', null, ['label' => 'L3_109 - Nombre total des membres ',])
            ->add('L3_110', null, ['label' => 'L3_110 - Nombre désagrégé par sexe ',])
            ->add('L3_111', null, ['label' => 'L3_111 - Nombre désagrégé par classe d’âge ',])
            ->add('L3_112', null, ['label' => 'L3_112 - Ministère de tutelle ',])
            ->add('L3_113', null, ['label' => 'L3_113 - Niveau hiérarchique : direction régionale, service, … ',])
            ->add('L3_114', null, ['label' => 'L3_114 - Niveau de la CTD : ',])
            ->add('L3_115', null, ['label' => 'L3_115 - Région : ',])
            ->add('L3_116', null, ['label' => 'L3_116 - Commune (s) : ',])
            ->add('L3_117', null, ['label' => 'L3_117 - Acteurs bénéficiaires : ',])
            ->add('L3_117_autre', null, ['label' => 'L3_117_autre - Si autre ?',])

            ->add('L3_130', null, ['label' => 'L3_130- Statut',])
            ->add('L3_131', null, ['label' => 'L3_131- Domaine d\'intervention',])
            ->add('L3_118', null, ['label' => 'L3_118 - Décrire les acteurs bénéficiaires de la bonne pratique (Résumé)',])
            ->add('L3_119', null, ['label' => 'L3_119 - Si vous avez travaillé avec des partenaires, énumérer les partenaires et décrivez brièvement  la nature du partenariat, ses origines. Et la manière dont ces acteurs ont contribué à la  bonne pratique. (200 mots)',])

            ->add('L4_26', null, ['label' => 'L4_26- Donner un mini-titre',])
            ->add('L4_26a', null, ['label' => 'L4_26a- Est-ce que la bonne pratique a abouti à un changement ou élaboration d’une loi liée à la thématique?',])
            ->add('L4_27', null, ['label' => 'L4_27- Si oui laquelle',])
            ->add('L4_28', null, ['label' => 'L4_28- Comment la relation entre les Communautés détentrices de la bonne pratique et les autres acteurs notamment s’améliorent-t-elles ?',])
            ->add('L4_29', null, ['label' => 'L4_29- Est-ce qu’il y a un changement de modalité opératoire au niveau des entités impactées par la bonne pratique (nouveau mode de gestion, nouveau mode opératoire, nouveau organigramme, création de plate forme…..)',])
            ->add('L4_30', null, ['label' => 'L4_30- Montrer avec des illustrations',])

            ->add('L4_1', null, ['label' => 'L4_1 - Donner un mini-titre',])
            ->add('L4_2', null, ['label' => 'L4_2 - Est-ce que la bonne pratique a provoqué des avantages économiques pour les bénéficiaires?',])
            ->add('L4_3', null, ['label' => 'L4_3 - Montrer avec des illustrations chiffrées?',])
            ->add('L4_4', null, ['label' => 'L4_4 - Amélioration des conditions des vies des revenus des ménages bénéficiaires',])
            ->add('L4_5', null, ['label' => 'L4_5 - Donner un mini-titre',])
            ->add('L4_6', null, ['label' => 'L4_6 - Comment la bonne pratique a amélioré la situation socio-économique (moyens de subsistance, revenus, etc….) et le bien-être (santé, sécurité alimentaire éducation, etc…) de la communauté?',])
            ->add('L4_6a', null, ['label' => 'L4_6a - Les personnes handicapées, les femmes et les jeunes ont-ils accès aux richesses, à l\'éducation, à l\'information et aux possibilités d\'innovation ?',])

            ->add('L4_7', null, ['label' => 'L4_7 - Montrer avec des illustrations chiffrées sur les avantages obtenus?',])
            ->add('L4_8', null, ['label' => 'L4_8 - Donner un mini-titre',])
            ->add('L4_9', null, ['label' => 'L4_9 - Est-ce que la bonne pratique a des effets sur la cohésion sociale, comment ?',])
            ->add('L4_10', null, ['label' => 'L4_10 - Qui sont les groupes bénéficiaires des effets / impacts?',])
            ->add('L4_11', null, ['label' => 'L4_11 - En quoi les bénéficiaires jouissent ces effets/ impacts ?',])
            ->add('L4_12', null, ['label' => 'L4_12 - Donner des illustrations chiffrées sur les avantages obtenus?',])
            ->add('L4_13', null, ['label' => 'L4_13 - Comment l’initiative a contribué à la gestion durable de l’environnement ?',])
            ->add('L4_13a', null, ['label' => 'L4_13a - Comment les membres de la communauté améliorent-ils, développent-ils et adoptent-ils de nouvelles pratiques de gestion de la biodiversité pour s\'adapter aux conditions changeantes, par exemple le changement climatique, la pression démographique, la dégradation des richesses ?',])

            ->add('L4_14', null, ['label' => 'L4_14 - Quels sont les produits ou services environnementaux améliorés à l’issu de la bonne pratique?',])
            ->add('L4_15', null, ['label' => 'L4_15 - Importance et étendue des écosystèmes affectés par la bonne pratique : superficie touchée par la bonne pratique?',])
            ->add('L4_16', null, ['label' => 'L4_16 - Hectares de terres bénéficiant de meilleures pratiques d’utilisation des terres et de techniques améliorées contre les changements climatiques?',])
            ->add('L4_17', null, ['label' => 'L4_17 - Donner des informations sur la superficie des terres sur lesquelles sont menées des pratiques de gestion durable des forêts ?',])
            ->add('L4_18', null, ['label' => 'L4_18 - Donner des informations sur la superficie des terres sur lesquelles sont menées des pratiques de gestion durable de l\'eau ?',])
            ->add('L4_19', null, ['label' => 'L4_19 - Donner des informations sur la superficie des terres sur lesquelles sont menées des pratiques de gestion durable de l\'agriculture ?',])
            ->add('L4_20', null, ['label' => 'L4_20 - Donner des informations sur la superficie de terres dégradées restaurées et réhabilitées?',])
            ->add('L4_21', null, ['label' => 'L4_21 - Donner des informations sur le nombre de communautés démontrant des pratiques de gestion durable des terres et forestière?',])
            ->add('L4_22', null, ['label' => 'L4_22 - Donner des informations sur la superficie des rivières /bassins lacustres appliquant des pratiques de gestion durable et contribuant à la mise en œuvre des PAS ?',])
            ->add('L4_23', null, ['label' => 'L4_23 - Donner des informations sur la superficie des zones marines / côtières ou des zones de pêche gérée durablement?',])
            ->add('L4_24', null, ['label' => 'L4_24 - Donner des informations sur les poids des produits chimiques évités?',])
            ->add('L4_25', null, ['label' => 'L4_25 - Décrire l\'effets de la bonne pratique sur l\'environnement (Résumé)',])
            
            ->add('L4_31', null, ['label' => 'L4_31- Donner des informations sur les capacités développées ',])
            ->add('L4_32', null, ['label' => 'L4_32- Décrire les effets du renforcement de capacité au niveau des communautés pour la gestion des richesses naturelles – par exemple une analyse, un suivi-évaluation, une formation, une capitalisation, une documentation, un partenariat, un réseautage ….. selon les  capacités développées',])
            ->add('L4_33', null, ['label' => 'L4_33- Comment le dialogue a impacté sur les points : Législation sur l’accès aux ressources foncières?',])
            ->add('L4_34', null, ['label' => 'L4_34- Comment le dialogue a impacté sur les points : Législation sur l’accès aux ressources naturelles?',])
            ->add('L4_35', null, ['label' => 'L4_35- Comment le dialogue a impacté sur les points : Législation sur l’accès aux ressources financières?',])
            ->add('L4_36', null, ['label' => 'L4_36- Comment le dialogue a impacté sur les points : Législation sur l’accès aux biens communs?',])
            ->add('L4_37', null, ['label' => 'L4_37- Comment le dialogue a impacté sur les points : Législation sur l’accès à l\'identité des Fokonolona?',])
            ->add('L4_38', null, ['label' => 'L4_38- Comment le dialogue a impacté sur les points : Défense des droits humains?',])
            ->add('L4_39', null, ['label' => 'L4_39- Comment le dialogue a impacté sur les points : Défense des droits culturels?',])
            ->add('L4_40', null, ['label' => 'L4_40- Comment le dialogue a impacté sur les points : Défense des droits environnementals?',])
            ->add('L4_41', null, ['label' => 'L4_41- Comment le dialogue a impacté sur les points : Défense des droits socio-économiques?',])
            ->add('L4_42', null, ['label' => 'L4_42- Comment le dialogue a impacté sur les points : Planification territoriale?',])
            ->add('L4_43', null, ['label' => 'L4_43- Comment le dialogue a impacté sur les points : Collaboration Fokonolona et OSC?',])
            ->add('L4_44', null, ['label' => 'L4_44- Comment le dialogue a impacté sur les points : Infrastructure et connectivité?',])
            ->add('L4_45', null, ['label' => 'L4_45- Comment le dialogue a impacté sur les points : Intercommunalité et gestion des ressources communes ?',])
            ->add('L4_46', null, ['label' => 'L4_46- Comment le dialogue a impacté sur les points : Accès aux prises de décisions au niveau National?',])
            ->add('L4_47', null, ['label' => 'L4_47- Comment le dialogue a impacté sur les points : Accès aux prises de décisions au niveau Régional?',])
            ->add('L4_48', null, ['label' => 'L4_48- Comment le dialogue a impacté sur les points : Accès aux prises de décisions au niveau Commune?',])
            ->add('L4_49', null, ['label' => 'L4_49- Comment le dialogue a impacté sur les points : Accès aux prises de décisions au niveau Local?',])
            ->add('L4_50', null, ['label' => 'L4_50- Veuillez décrire les effets de la bonne pratique sur la reconnaissance des APAC?',])
            ->add('L4_51', null, ['label' => 'L4_51- Veuillez décrire les effets de la bonne pratique sur l’habitat de la nature notamment pour les espèces endémiques?',])
            ->add('L4_52', null, ['label' => 'L4_52- Veuillez décrire les effets de la bonne pratique sur la préservation des cultures locales?',])
            ->add('L4_53', null, ['label' => 'L4_53- Veuillez décrire les effets de la bonne pratique sur la  prise de décision au sein du Fokonolona?',])
            
            ->add('L5_1', null, ['label' => 'L5_1 - Donnez un mini-titre récapitulant les changements',])
            ->add('L5_2', null, ['label' => 'L5_2 - Sous quel forme l\'impact de la bonne pratique?',])
            ->add('L5_2_autre', null, ['label' => 'L5_2_autre - Si autre ?',])
            
            ->add('L5_3', null, ['label' => 'L5_3- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique au niveau des communautés locales et ses composantes : chez les  leaders, les hommes, les femmes, les enfants, les différents groupes telles que COBA, …. :',])
            ->add('L5_4', null, ['label' => 'L5_4- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique au niveau des communautés des APAC :',])
            ->add('L5_5', null, ['label' => 'L5_5- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique au niveau du peuple autochtone :',])
            ->add('L5_6', null, ['label' => 'L5_6- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique au niveau des OSC  ou des organisations fédératives :',])
            ->add('L5_7', null, ['label' => 'L5_7- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique au niveau CTD :',])
            ->add('L5_8', null, ['label' => 'L5_8- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique au niveau STD : ',])
            ->add('L5_9', null, ['label' => 'L5_9- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique au niveau du secteur privé :',])
            ->add('L5_10', null, ['label' => 'L5_10- Veuillez décrire les changements de comportement engendrés par la mise en application de la bonne pratique dans d\'autres niveau :',])
                        
            ->add('L6_1', null, ['label' => 'L6_1 - Est-ce que la bonne pratique a touché les groupes exclus : personnes handicapées, personnes âgées, jeunes….Si oui comment ?',])
            ->add('L6_2', null, ['label' => 'L6_2 - Quels sont les rôles des personnes exclus dans la mise en œuvre de la bonne pratique?',])
            ->add('L6_3', null, ['label' => 'L6_3 - Est-ce que la bonne pratique a relation avec la prévention ou lutte contre le COVID- 19?',])
            ->add('L6_4', null, ['label' => 'L6_4 - Comment se montre l’équilibre entre homme et femmes dans la conception et la mise en œuvre de la bonne pratique?',])
          
            ->add('L6_4a', null, ['label' => 'L6_4a - S’il y en a comment s’améliore la prise de décision des femmes dans la gouvernance des ressources naturelles?',])

          
            ->add('L6_5', null, ['label' => 'L6_5 - Quelles sont les répartitions des tâches ? Quels avantages sociaux obtenus avec la répartition ? ',])
            ->add('L6_6', null, ['label' => 'L6_6 - Décrire  comment la bonne pratique a contribué à l’autonomisation des femmes dans son approche vis-à-vis du bien-être, des moyens de subsistance et de  la préservation de l’environnement et de la communauté?',])
            ->add('L7_1', null, ['label' => 'L7_1 - D’après la bonne pratique : quelles sont les leçons tirées par la communauté ou les entités détentrices de la bonne pratique (énumérez)?',])
            ->add('L8_1', null, ['label' => 'L8_1 - Décrire la durabilité environnementale de la bonne pratique : renforcement de la vie harmonieuse entre l’Homme et la Nature',])
            ->add('L8_2', null, ['label' => 'L8_2 - Décrire la stabilité sociale engendrée par la bonne pratique  ',])
            ->add('L8_3', null, ['label' => 'L8_3 - Décrire la durabilité culturelle : Transmission de génération en génération',])
            ->add('L9_1', null, ['label' => 'L9_1 - Comment la communauté partage la bonne pratique avec les autres communautés ou les entités homologues ?',])
            ->add('L9_2', null, ['label' => 'L9_2 - Sous quelle forme ?',])
            ->add('L9_2a', null, ['label' => 'L9_2a - S’il y en a décrire le système communautaire de documentation, d\'échange et d\'acquisition de connaissances d\'origine extérieure?  ?',])
            ->add('L9_3', null, ['label' => 'L9_3 - Enumérez le(s) partenaire(s) média avec qui vous avez travaillé?',])
            ->add('L9_4', null, ['label' => 'L9_4 - Comment avez-vous fait pour mettre en exergue la visibilité de GEF SGP?',])
            ->add('L9_5', null, ['label' => 'L9_5 - Comment les autres communautés agissent par rapport aux bonnes pratiques?',])
            ->add('L9_6', null, ['label' => 'L9_6 - Quels sont les moyens requis pour assurer le partage des bonnes pratiques : humain, financier?',])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CapitalisationPartII::class,
        ]);
    }
}
